### PR TITLE
vendor: update sparse-tools

### PR DESCRIPTION
**Pull request by ChanYiLin**
Issue: [longhorn/longhorn#4305](https://github.com/longhorn/longhorn/issues/4305)
Depends on: https://github.com/longhorn/sparse-tools/pull/93

### CODE REVIEW

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
Merge this after e2e finished.

**Comment by ChanYiLin** [comment]
There is an issue in the e2e test, let me check (`test_migration_with_restore_volume`)

**Comment by ChanYiLin** [comment]
Weird, I reran again and it passed.
Let me run the coretest again

**Comment by innobead** [comment]
Is it flaky test?

cc @longhorn/qa

**Comment by ChanYiLin** [comment]
the previous one passed, but there is another failure
I still don't think this is related to this PR 
```
=================================== FAILURES ===================================
_________________ test_backup_failed_disable_auto_cleanup[s3] __________________

set_random_backupstore = None
client = <longhorn.Client object at 0x7f2cd3ebb970>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f2cc749aa60>
volume_name = 'longhorn-testvol-ko5s2k'

    @pytest.mark.coretest  # NOQA
    def test_backup_failed_disable_auto_cleanup(set_random_backupstore,  # NOQA
                                            client, core_api, volume_name):  # NOQA
        """
        Test the failed backup would be automatically deleted.
    
        1.    Set the default setting `backupstore-poll-interval` to 60 (seconds)
        2.    Set the default setting `failed-backup-ttl` to 0
        3.    Create a volume and attach to the current node
        4.    Create a empty backup for creating the backup volume
        5.    Write some data to the volume
        6.    Create a backup of the volume
        7.    Crash all replicas
        8.    Wait and check if the backup failed
        9.    Wait and check if the backup was not deleted.
        10.   Cleanup
        """
>       backup_name = backup_failed_cleanup(client, core_api, volume_name, 256*Mi,
                                            failed_backup_ttl="0")

test_basic.py:4954: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_basic.py:4896: in backup_failed_cleanup
    common.wait_for_backup_state(client, volume_name,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7f2cd3ebb970>
volume_name = 'longhorn-testvol-ko5s2k'
predicate = <function backup_failed_cleanup.<locals>.backup_inprogress_predicate at 0x7f2cc74bd430>
retry_count = 300

    def wait_for_backup_state(client, volume_name, predicate,
                              retry_count=RETRY_BACKUP_COUNTS):
        completed = False
        for i in range(retry_count):
            v = client.by_id_volume(volume_name)
            for b in v.backupStatus:
                if predicate(b):
                    completed = True
                    break
            if completed:
                break
            time.sleep(RETRY_BACKUP_INTERVAL)
>       assert completed is True
E       AssertionError

common.py:2904: AssertionError
```

**Comment by ChanYiLin** [comment]
I just used **master-head** for all the images but still got two failures, same as using my testing image
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3429/consoleFull

**Comment by ChanYiLin** [comment]
It seems to be flaky test, I passed by rerunning the tests more than 1 times

**Review by innobead — APPROVED** [review]

**Comment by ChanYiLin** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
