### PR TITLE
feat(backupbackingimage): add parameters to backup backing image create proto

### PR DESCRIPTION
**Pull request by ChanYiLin**
ref: https://github.com/longhorn/longhorn/issues/8884

update
- get the parameters from the grpc
- pass the parameters to the backupstore so it can get the `secret`, `secretNamespace`

### CODE REVIEW

**Review by derekbit — DISMISSED** [review]
LGTM

**Comment by derekbit** [comment]
@ChanYiLin Need to resolve conflicts first.

**Comment by derekbit** [comment]
@ChanYiLin Need to resolve the conflicts. Thanks.

**Comment by ChanYiLin** [comment]
> @ChanYiLin Need to resolve the conflicts. Thanks.

- updated the longhorn/types vendor
- resolved conflicts

**Review by derekbit — APPROVED** [review]
LGTM

**Pull request merged**
